package com.app.accounts.entity;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@Table(name = "ACCOUNTSTBL")
public class AccountsEntity extends BaseEntity {

    @Id
    @Column
    private Long accountId; //BIGINT GENERATED BY DEFAULT AS IDENTITY,
    @Column
    private Long customerId;// BIGINT NOT NULL,
    @Column
    private String accountNumber; //VARCHAR(20) NOT NULL,
    @Column
    private String accountType; //VARCHAR(15) NOT NULL,
    @Column
    private BigDecimal balance; //NUMERIC(15, 2) DEFAULT 0.00,
    @Column
    private String status = "OPEN";// VARCHAR(15) DEFAULT 'OPEN',
    // Defines the owning side of the relationship
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customerId", nullable = false, insertable = false, updatable = false)
    private CustomersEntity customer;

}
