server:
  port: 8085
spring:
  application:
    name: accounts

  mvc:
    api-version:
      strategy:
      path-segment: 1

  output:
    ansi:
      enabled: always

  config:
    import: "optional:configserver:"

  datasource:
    url: jdbc:h2:mem:mydb
    #    url: jdbc:h2:file:./H2DBFiles/EcommerceDatabase
    username: user
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        default_schema: COMM_BANKING_SYSTEM
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console

