-- Create optional custom schema if not using the default PUBLIC schema
CREATE SCHEMA IF NOT EXISTS comm_banking_system;
SET SCHEMA comm_banking_system;

-- Drop tables if they exist to allow clean local testing/re-runs
DROP TABLE IF EXISTS accountsTbl;
DROP TABLE IF EXISTS customersTbl;

-- 1. Customers Master Table
CREATE TABLE customersTbl (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20),
    status VARCHAR(15) DEFAULT 'ACTIVE',
    created_by VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(50),
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_customers PRIMARY KEY (customer_id),
    CONSTRAINT uq_customer_email UNIQUE (email),
    CONSTRAINT chk_customer_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'INACTIVE', 'DELETED'))
);

-- 2. Accounts Table (Linked to Customers via Foreign Key)
CREATE TABLE accountsTbl (
    account_id BIGINT,
    customer_id BIGINT NOT NULL,
    account_number VARCHAR(20) NOT NULL,
    account_type VARCHAR(15) NOT NULL,
    balance NUMERIC(15, 2) DEFAULT 0.00,
    status VARCHAR(15) DEFAULT 'OPEN',
    created_by VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(50) ,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_accounts PRIMARY KEY (account_id),
    CONSTRAINT uq_account_number UNIQUE (account_number),
    CONSTRAINT fk_accounts_customer FOREIGN KEY (customer_id) REFERENCES customersTbl(customer_id) ON DELETE RESTRICT,
    CONSTRAINT chk_account_type CHECK (account_type IN ('SAVINGS', 'CHECKING', 'CREDIT', 'LOAN')),
    CONSTRAINT chk_account_status CHECK (status IN ('OPEN', 'CLOSED', 'FROZEN'))
);

-- Indexes for Query Optimization
CREATE INDEX idx_customers_email ON customersTbl(email);
CREATE INDEX idx_accounts_customer ON accountsTbl(customer_id);
CREATE INDEX idx_accounts_number ON accountsTbl(account_number);
CREATE SEQUENCE IF NOT EXISTS COMM_BANKING_SYSTEM.customer_sequence START WITH 1001 INCREMENT BY 1;

